name: CI
on:
  pull_request:
    branches: [main]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # 更新到v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'pnpm' # 启用pnpm缓存支持

      # 修复关键点：必须显式安装pnpm
      - name: Install pnpm
        run: npm install -g pnpm@latest # 安装最新稳定版

      - name: Cache
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store  # pnpm专用缓存目录
            **/node_modules
          # 使用pnpm-lock代替yarn.lock
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Installing Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile # 推荐使用frozen模式

      - name: Running Lint
        run: pnpm lint
